name: radicle
services:
  node:
    image: nausicaea/radicle-node:local
    build:
      dockerfile: node.Dockerfile
    environment:
      RAD_DEFAULT_SEEDING_POLICY: block
    volumes:
      - data:/var/lib/radicle
    ports:
      - 127.0.0.1:8778:8776/tcp

  httpd:
    image: nausicaea/radicle-httpd:local
    build:
      dockerfile: httpd.Dockerfile
    volumes:
      - data:/var/lib/radicle:ro
    ports:
      - 127.0.0.1:8080:80/tcp
    depends_on:
      - node

volumes:
  data: {}
