#!/bin/sh

# Usage: ./map-target.sh linux/amd64
# Or:    TARGET_PLATFORM=linux/arm64 ./map-target.sh
# Attribution: Generated by ChatGPT on 2025-08-05 
# Source: https://chatgpt.com/share/689198ff-a0bc-8013-8629-de4cf081809a

# Prefer the first argument, else fall back to $TARGETPLATFORM
PLATFORM="${1:-$TARGETPLATFORM}"

case "$PLATFORM" in
  linux/amd64)
    echo x86_64-unknown-linux-musl
    ;;
  linux/arm64)
    echo aarch64-unknown-linux-musl
    ;;
  *)
    echo "Unsupported TARGET_PLATFORM: $PLATFORM" >&2
    exit 1
    ;;
esac
